Use get-pip.py instead

diff --git a/examples/django-deployment/Makefile b/examples/django-deployment/Makefile
--- a/examples/django-deployment/Makefile
+++ b/examples/django-deployment/Makefile
@@ -38,18 +38,19 @@ compile-packages:
 complete-install:
 
 ifeq (${PIP_PATH},)
-	python get-pip.py
+	curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
+	python ./get-pip.py
 endif
 
 ifeq (${PG_CONFIG_PATH},)
-	ifeq ($(shell uname -s), Linux)
-		apt-get -y install postgresql
-	else ifeq ($(shell uname -s), Darwin)
-		brew install postgresql
-	else
-		echo "Error! redis not supported by $(shell uname -s)"
-		exit 125
-	endif
+ifeq ($(shell uname -s), Linux)
+	apt-get -y install postgresql
+else ifeq ($(shell uname -s), Darwin)
+	brew install postgresql
+else
+	echo "Error! redis not supported by $(shell uname -s)"
+	exit 125
+endif
 endif
 
 ifneq ($(shell pip list | grep pipenv | cut -d ' ' -f1),pipenv)
