🐛 Add support for pipenv and pg

diff --git a/examples/django-deployment/Makefile b/examples/django-deployment/Makefile
--- a/examples/django-deployment/Makefile
+++ b/examples/django-deployment/Makefile
@@ -1,4 +1,6 @@
 HOME_DIR = $(shell pwd)
+USER_BIN_PATH = $(shell python3 -m site --user-base)/bin
+PG_CONFIG_PATH = $(shell which pg_config)
 
 .PHONY: install
 install:
@@ -33,7 +35,29 @@ compile-packages:
 
 .PHONY: complete-install
 complete-install:
-	make compile-packages && make install
+
+ifeq (${PG_CONFIG_PATH},)
+ifeq ($(shell uname -s), Linux)
+	apt-get -y install postgresql
+else ifeq ($(shell uname -s), Darwin)
+	brew install postgresql
+else
+	echo "Error! redis not supported by $(shell uname -s)"
+	exit 125
+endif
+endif
+
+ifneq ($(shell pip list | grep pipenv | cut -d ' ' -f1),pipenv)
+	pip install --user pipenv && \
+	export PATH=${PATH}:${USER_BIN_PATH} && \
+	make compile-packages && \
+	make install
+else
+	export PATH=${PATH}:${USER_BIN_PATH} && \
+  make compile-packages && make install
+endif
+
+	exit 1
 ifeq ($(shell uname -s), Linux)
 	apt-get install redis
 else ifeq ($(shell uname -s),Darwin)
